require 'minitest/autorun'
require 'sortable'
require './lib/linked_list/linked_list'
require './lib/linked_list/node_linked_list'
require './lib/stack/link_stack'
require './lib/queue/link_queue'
require './lib/hash/hash_table'
